GymShop/GymShop/urls.py
from django.contrib import admin
from django.urls import path, include
from alledrogo.views import *


urlpatterns = [

    path('admin/', admin.site.urls),
    path('admin', admin.site.urls),
    path('', include('alledrogo.urls')),
    path('', home, name='home'),
    path('kategoria/<id>/', kategoria, name='kategoria'),
    path('produkt/<int:id>/', produkt_detail, name='produkt_detail'),
    ]

GymShop/alledrogo/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .views import home, login, register, profile, logout, produkt_detail_view, firm_login,wystaw_produkt
from . import views

urlpatterns = [
    path('', home, name='home'),
    path('login/', login, name='login'),
    path('register/', register, name='register'),
    path('profile/', profile, name='profile'),
    path('logout/', logout, name='logout'),
    path('produkt/<int:produkt_id>/', produkt_detail_view, name='produkt_detail'),
    path('koszyk/', views.koszyk, name='koszyk'),
    path('koszyk/dodaj/<int:produkt_id>/', views.dodaj_do_koszyka, name='dodaj_do_koszyka'),
    path('koszyk/update/<int:pozycja_id>/', views.update_pozycja_koszyka, name='update_pozycja_koszyka'),
    path('koszyk/remove/<int:pozycja_id>/', views.remove_item_from_cart, name='remove_item_from_cart'),
    path('zamowienie/', views.zamowienie, name='zamowienie'),
    path('zamowienia/', views.zamowienia, name='zamowienia'),
    path('orders/', views.zamowienia, name='orders'),
    path('firm/login/', firm_login, name='firm_login'),
    path('firm/register/', views.company_register, name='company_register'),
    path('wystaw-produkt/', wystaw_produkt, name='wystaw_produkt'),
    path('produkt/usun/<int:produkt_id>/', views.usun_produkt, name='usun_produkt'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

GymShop/alledrogo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Avg  # Import Avg for calculating average rating

class Firma(models.Model):
    id = models.AutoField(primary_key=True)
    nazwa = models.CharField(max_length=256)
    opis = models.TextField()
    ikona = models.ImageField(upload_to='media/ikony_firm', null=True, blank=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='firma', null=True, blank=True)

    def __str__(self):
        return self.nazwa

class Kategoria(models.Model):
    id = models.AutoField(primary_key=True)
    nazwa = models.CharField(max_length=256)
    opis = models.TextField()

    def __str__(self):
        return self.nazwa

class Produkt(models.Model):
    id = models.AutoField(primary_key=True)
    nazwa = models.CharField(max_length=256)
    opis = models.TextField()
    cena = models.FloatField()

    srednia_ocen = models.FloatField(default=0)
    kategoria = models.ForeignKey(Kategoria, on_delete=models.CASCADE)
    firma = models.ForeignKey(Firma, on_delete=models.CASCADE, null=True, blank=True)
    zdjecie = models.ImageField(upload_to='media/zdjecia_produktow', null=True, blank=True)

    def __str__(self):
        return self.nazwa

class Zamowienie(models.Model):
    id = models.AutoField(primary_key=True)
    produkty_z_iloscia = models.ManyToManyField(Produkt, through='PozycjaZamowienia', related_name='zamowienia_z_iloscia')
    klient = models.ForeignKey(User, on_delete=models.CASCADE)
    data_zamowienia = models.DateTimeField(auto_now_add=True)
    data_dostarczenia = models.DateTimeField()
    imie = models.CharField(max_length=100, default='brak')
    nazwisko = models.CharField(max_length=100, default='brak')
    ulica = models.CharField(max_length=255, default='brak')
    miasto = models.CharField(max_length=100, default='brak')
    kod_pocztowy = models.CharField(max_length=6, default='brak')
    numer_telefonu = models.CharField(max_length=15, default='brak')
    notatki = models.TextField(blank=True, null=True)

    def __str__(self):
        return f'{self.klient} - {self.data_zamowienia}'

class Ocena(models.Model):
    id = models.AutoField(primary_key=True)
    produkt = models.ForeignKey(Produkt, on_delete=models.CASCADE)
    klient = models.ForeignKey(User, on_delete=models.CASCADE)
    ocena = models.IntegerField(choices=[(i, i) for i in range(1, 6)])
    komentarz = models.TextField()

    def __str__(self):
        return str(self.produkt) + ' ' + str(self.ocena) + ' ' + str(self.komentarz)

class Koszyk(models.Model):
    id = models.AutoField(primary_key=True)
    klient = models.ForeignKey(User, on_delete=models.CASCADE)
    data_utworzenia = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.klient) + ' ' + str(self.data_utworzenia)

class PozycjaKoszyka(models.Model):
    koszyk = models.ForeignKey(Koszyk, on_delete=models.CASCADE, related_name='pozycje')
    produkt = models.ForeignKey('Produkt', on_delete=models.CASCADE)
    ilosc = models.PositiveIntegerField(default=1)

    def __str__(self):
        return f"{self.produkt.nazwa} x {self.ilosc}"

    @property
    def cena_calosciowa(self):

        return round(self.produkt.cena * self.ilosc, 2)

class PozycjaZamowienia(models.Model):
    zamowienie = models.ForeignKey(Zamowienie, on_delete=models.CASCADE)
    produkt = models.ForeignKey(Produkt, on_delete=models.CASCADE)
    ilosc = models.PositiveIntegerField(default=1)

    def cena_calosciowa(self):
        return self.ilosc * self.produkt.cena

GymShop/alledrogo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.models import User
from .forms import CustomLoginForm, CustomRegisterForm, CompanyRegisterForm, ZamowienieForm , FirmLoginForm, CustomUserRegisterForm , ProduktForm
from .models import Produkt, Kategoria, Koszyk, PozycjaKoszyka, Firma, Zamowienie, PozycjaZamowienia
from django.http import HttpResponse, JsonResponse
from django.db.models import F, Q, Avg, Sum  # Import F, Q, Avg
from django.utils import timezone  # Import timezone
from datetime import timedelta
from .models import Ocena  # Import Ocena model


def usun_produkt(request, produkt_id):
    produkt = get_object_or_404(Produkt, id=produkt_id)
    if request.user.firma == produkt.firma:
        produkt.delete()

        return redirect('profile')
    return redirect('home')

def wystaw_produkt(request):
    if not hasattr(request.user, 'firma'):
        return redirect('profile')

    if request.method == 'POST':
        form = ProduktForm(request.POST, request.FILES)
        if form.is_valid():
            produkt = form.save(commit=False)
            produkt.firma = request.user.firma
            produkt.save()
            return redirect('profile')
    else:
        form = ProduktForm()

    return render(request, 'wystaw_produkt.html', {'form': form})

def company_register(request):
    if request.method == 'POST':

        user_form = CustomUserRegisterForm(request.POST)
        company_form = CompanyRegisterForm(request.POST, request.FILES)

        if user_form.is_valid() and company_form.is_valid():

            user = user_form.save()


            firma = company_form.save(commit=False)
            firma.user = user
            firma.save()


            auth_login(request, user)
            return redirect('home')
    else:
        user_form = CustomUserRegisterForm()
        company_form = CompanyRegisterForm()

    return render(request, 'company_register.html', {
        'user_form': user_form,
        'company_form': company_form,
    })




def firm_login(request):
    if request.method == 'POST':
        form = FirmLoginForm(request, data=request.POST)
        if form.is_valid():
            username_or_email = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username_or_email, password=password)


            if user and hasattr(user, 'firma'):
                auth_login(request, user)
                return redirect('firm_admin_panel')
            else:
                form.add_error(None, "Brak dostępu do panelu firmowego.")
    else:
        form = FirmLoginForm()
    return render(request, 'firm_login.html', {'form': form})


def register(request):
    if request.method == 'POST':
        user_form = CustomRegisterForm(request.POST)
        company_form = CompanyRegisterForm(request.POST, request.FILES)

        if user_form.is_valid() and company_form.is_valid():
            user = user_form.save()
            user.set_password(user_form.cleaned_data["password"])
            user.save()


            firma = company_form.save(commit=False)
            firma.user = user
            firma.save()

            auth_login(request, user)
            return redirect('home')
    else:
        user_form = CustomRegisterForm()
        company_form = CompanyRegisterForm()

    return render(request, 'register.html', {'user_form': user_form, 'company_form': company_form})


def remove_item_from_cart(request, pozycja_id):
    pozycja = get_object_or_404(PozycjaKoszyka, id=pozycja_id)
    pozycja.delete()
    return redirect('koszyk')

def company_profile(request):
    firma = Firma.objects.get(user=request.user)
    return render(request, 'company_profile.html', {'firma': firma})


def update_pozycja_koszyka(request, pozycja_id):
    if request.method == 'POST':
        pozycja = get_object_or_404(PozycjaKoszyka, id=pozycja_id)
        # Pobieramy ilość z formularza (może być ręcznie wpisana lub zmieniona)
        ilosc = int(request.POST.get('ilosc', pozycja.ilosc))

        if ilosc <= 0:
            pozycja.delete()  # Jeśli ilość <= 0, usuwamy produkt z koszyka
        else:
            pozycja.ilosc = ilosc
            pozycja.save()

    return redirect('koszyk')


def home(request):
    # Pobierz wszystkie kategorie
    kategorie = Kategoria.objects.all()
    firmy = Firma.objects.all()  # Pobierz wszystkie firmy

    # Pobierz wszystkie produkty
    produkty = Produkt.objects.all()

    # Wyszukiwanie po nazwie produktu
    search_query = request.GET.get('search', '')
    if search_query:
        produkty = produkty.filter(nazwa__icontains=search_query)

    # Filtracja po kategorii
    wybrana_kategoria_id = request.GET.get('kategoria')
    if wybrana_kategoria_id:
        produkty = produkty.filter(kategoria_id=wybrana_kategoria_id)

    # Filtracja po firmie
    wybrana_firma_id = request.GET.get('firma')
    if wybrana_firma_id:
        produkty = produkty.filter(firma_id=wybrana_firma_id)

    # Sortowanie po cenie
    sortowanie = request.GET.get('sortowanie', 'cena_rosnaco')
    if sortowanie == 'cena_rosnaco':
        produkty = produkty.order_by('cena')
    elif sortowanie == 'cena_malejaco':
        produkty = produkty.order_by('-cena')

    # Filtracja po przedziale cenowym
    cena_min = request.GET.get('cena_min')
    cena_max = request.GET.get('cena_max')

    if cena_min:
        produkty = produkty.filter(cena__gte=float(cena_min))
    if cena_max:
        produkty = produkty.filter(cena__lte=float(cena_max))

    context = {
        'produkty': produkty,
        'kategorie': kategorie,
        'firmy': firmy,  # Dodaj firmy do kontekstu
        'wybrana_kategoria': wybrana_kategoria_id,
        'wybrana_firma': wybrana_firma_id,  # Dodaj wybraną firmę do kontekstu
        'sortowanie': sortowanie,
        'cena_min': cena_min,
        'cena_max': cena_max,
        'search_query': search_query,
    }

    return render(request, 'home.html', context)

def produkt_detail(request, id):
    produkt = get_object_or_404(Produkt, id=id)
    return render(request, 'produkt_detail.html', {'produkt': produkt})

def kategoria(request, id):
    kategoria_user = Kategoria.objects.get(pk=id)
    return HttpResponse(kategoria_user.nazwa)

def login(request):
    if request.method == 'POST':
        form = CustomLoginForm(request, data=request.POST)
        if form.is_valid():
            username_or_email = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')

            user = authenticate(request, username=username_or_email, password=password)
            if user is not None:
                auth_login(request, user)

                # Sprawdzenie, czy użytkownik ma przypisaną firmę
                try:
                    firma = user.firma  # Związanie z modelem Firma
                    request.session['firma_id'] = firma.id  # Można przechować ID firmy w sesji
                    return redirect('home')  # Przekierowanie na stronę główną
                except Firma.DoesNotExist:
                    return redirect('home')  # Jeśli użytkownik nie ma firmy, przejdź na stronę główną
    else:
        form = CustomLoginForm()

    return render(request, 'login.html', {'form': form})

def register(request):
    if request.method == 'POST':
        form = CustomRegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request, user)
            return redirect('home')
    else:
        form = CustomRegisterForm()
    return render(request, 'register.html', {'form': form})



def profile(request):

    ilosc_sprzedanych_produktow = 0
    produkty = []
    firma = None

    if request.user.is_authenticated and hasattr(request.user, 'firma'):
        firma = request.user.firma
        produkty = firma.produkt_set.all()

        sprzedane_produkcje = PozycjaZamowienia.objects.filter(produkt__firma=firma)

        ilosc_sprzedanych_produktow = sprzedane_produkcje.aggregate(Sum('ilosc'))['ilosc__sum'] or 0

    return render(request, 'profile.html', {

        'ilosc_sprzedanych_produktow': ilosc_sprzedanych_produktow,
        'produkty': produkty,
        'firma': firma,
    })

def logout(request):
    auth_logout(request)
    return redirect('home')

def dodaj_do_koszyka(request, produkt_id):
    produkt = get_object_or_404(Produkt, id=produkt_id)
    ilosc = int(request.POST.get('quantity', 1))
    koszyk, created = Koszyk.objects.get_or_create(klient=request.user)

    pozycja, created = PozycjaKoszyka.objects.get_or_create(koszyk=koszyk, produkt=produkt)
    if not created:
        pozycja.ilosc = F('ilosc') + ilosc
    else:
        pozycja.ilosc = ilosc
    pozycja.save()

    return redirect('koszyk')

def koszyk(request):
    koszyk, created = Koszyk.objects.get_or_create(klient=request.user)
    pozycje = koszyk.pozycje.select_related('produkt')
    total = sum([pozycja.cena_calosciowa for pozycja in pozycje])  # Fix variable name
    return render(request, 'koszyk.html', {'pozycje': pozycje, 'total': total})

def zamowienie(request):
    koszyk, created = Koszyk.objects.get_or_create(klient=request.user)
    pozycje = koszyk.pozycje.select_related('produkt')
    total = round(sum([pozycja.cena_calosciowa for pozycja in pozycje]), 2)
    
    if not pozycje.exists():
        return redirect('koszyk')  # Redirect to basket if it's empty
    
    if request.method == 'POST':
        form = ZamowienieForm(request.POST)
        if form.is_valid():
            zamowienie = Zamowienie.objects.create(
                klient=request.user,
                imie=form.cleaned_data['imie'],
                nazwisko=form.cleaned_data['nazwisko'],
                ulica=form.cleaned_data['ulica'],
                miasto=form.cleaned_data['miasto'],

GymShop/alledrogo/templates/company_register.html
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <title>Rejestracja firmy</title>
</head>
<body>
    {% extends "template.html" %}
    {% block content %}
    <h2>Rejestracja użytkownika i firmy</h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <h3>Rejestracja użytkownika</h3>
        {{ user_form.as_p }}
        <h3>Rejestracja firmy</h3>
        {{ company_form.as_p }}
        <button type="submit">Zarejestruj się</button>
    </form>
{%endblock%}
</body>
</html>

GymShop/alledrogo/templates/firm_login.html
<!DOCTYPE html>
<html>
<head>
    <title>Logowanie firmy</title>
</head>
<body>
    {% extends "template.html" %}
    {% block content %}
    <form method="post">
        <h2>Logowanie firmy</h2>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Zaloguj</button>
    </form>
    {% endblock %}
</body>
</html>

GymShop/alledrogo/templates/home.html
{% extends "template.html" %}
{% load static %}
{% block content %}
<div id="glowny">
    <div id="baner">
        <img src="{% static 'images/blackweeks.jpg' %}" height="300px" />
    </div>

    <div id="filters-top-bar" class="responsive-filters">
        <form method="get" action=".">
            <select name="kategoria" id="kategoria" class="filter-select" onchange="this.form.submit()">
                <option value="">Wszystkie kategorie</option>
                {% for kategoria in kategorie %}
                <option value="{{ kategoria.id }}" {% if wybrana_kategoria == kategoria.id %}selected{% endif %}>
                    {{ kategoria.nazwa }}
                </option>
                {% endfor %}
            </select>
            <select name="firma" id="firma" class="filter-select" onchange="this.form.submit()">
                <option value="">Wszystkie firmy</option>
                {% for firma in firmy %}
                <option value="{{ firma.id }}" {% if wybrana_firma == firma.id %}selected{% endif %}>
                    {{ firma.nazwa }}
                </option>
                {% endfor %}
            </select>
            <select name="sortowanie" id="sortowanie" class="filter-select" onchange="this.form.submit()">
                <option value="cena_rosnaco" {% if sortowanie == 'cena_rosnaco' %}selected{% endif %}>Cena: od najniższej</option>
                <option value="cena_malejaco" {% if sortowanie == 'cena_malejaco' %}selected{% endif %}>Cena: od najwyższej</option>
            </select>
            <label for="cena_min" class="filter-label">Cena od:</label>
            <input type="number" name="cena_min" id="cena_min" class="filter-input" value="{{ cena_min }}" placeholder="Min. cena" />
            <label for="cena_max" class="filter-label">Cena do:</label>
            <input type="number" name="cena_max" id="cena_max" class="filter-input" value="{{ cena_max }}" placeholder="Max. cena" />
            <button type="submit" class="filter-button">Filtruj</button>
        </form>
    </div>

    <div class="produkty-container">
        {% for produkt in produkty %}
        <div class="produkt" onclick="window.location.href='{% url 'produkt_detail' produkt.id %}'">
            <a href="{% url 'produkt_detail' produkt.id %}" class="produkt-link">
                <div class="image-container">
                    {% if produkt.zdjecie %}
                    <img src="{{ produkt.zdjecie.url }}" alt="{{ produkt.nazwa }}" />
                    <div class="image-overlay" style="background-image: url('{{ produkt.zdjecie.url }}');"></div>
                    {% endif %}
                </div>
                <h2>{{ produkt.nazwa }}</h2>
                <p>{{ produkt.cena|floatformat:2 }} PLN</p>
            </a>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

GymShop/alledrogo/templates/koszyk.html
{% extends "template.html" %}
{% load static %}
{% block content %}

<div class="cart-container">
    <h1 class="cart-title">Twój Koszyk</h1>
    <div class="cart-items">
        {% for pozycja in pozycje %}
        <div class="cart-item" id="cart-item-{{ pozycja.id }}">
            <div class="item-image">
                {% if pozycja.produkt.zdjecie %}
                <img src="{{ pozycja.produkt.zdjecie.url }}" />
                {% endif %}
            </div>
            <div class="item-details">
                <h3>{{ pozycja.produkt.nazwa }}</h3>
                <p>Cena: {{ pozycja.produkt.cena|floatformat:2 }} PLN</p>

                <form action="{% url 'update_pozycja_koszyka' pozycja.id %}" method="POST" class="update-form">
                    {% csrf_token %}
                    <p>Ilość:
                        <button type="button" class="decrease-quantity" data-id="{{ pozycja.id }}" {% if pozycja.ilosc <= 1 %}disabled{% endif %}>-</button>
                        <input type="number" class="quantity-input" name="ilosc" value="{{ pozycja.ilosc }}" min="1" style="width: 50px;" />
                        <button type="button" class="increase-quantity" data-id="{{ pozycja.id }}">+</button>
                    </p>
                </form>
                <p>Łącznie: {{ pozycja.cena_calosciowa|floatformat:2 }} PLN</p>
            </div>
            <div class="item-actions">
                <form action="{% url 'remove_item_from_cart' pozycja.id %}" method="POST" class="remove-form">
                    {% csrf_token %}
                    <button type="submit" class="remove-item">
                        <img src="{% static 'images/trash-can.png' %}" alt="Usuń" class="trash-can-icon" />
                    </button>
                </form>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="cart-summary">
        <h2>Łączna kwota: {{ total|floatformat:2 }} PLN</h2>
        <div class="checkout-buttons">
            <a href="{% url 'zamowienie' %}" class="btn checkout-btn">Dostawa i płatność</a>
            <a href="{% url 'home' %}" class="btn continue-btn">Kontynuuj zakupy</a>
        </div>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        document.querySelectorAll('.decrease-quantity').forEach(button => {
            button.addEventListener('click', function() {
                const form = this.closest('.update-form');
                const input = form.querySelector('input[name="ilosc"]');
                if (input.value > 1) {
                    input.value = parseInt(input.value) - 1;
                    form.submit();
                }
            });
        });

        document.querySelectorAll('.increase-quantity').forEach(button => {
            button.addEventListener('click', function() {
                const form = this.closest('.update-form');
                const input = form.querySelector('input[name="ilosc"]');
                input.value = parseInt(input.value) + 1;
                form.submit();
            });
        });

        document.querySelectorAll('.item-actions').forEach(action => {
            action.addEventListener('click', function() {
                const form = this.querySelector('.remove-form');
                form.submit();
            });
        });
    });
</script>

{% endblock %}

GymShop/alledrogo/templates/login.html
<!DOCTYPE html>
<html>
<head>
    <title>Logowanie</title>
</head>
<body>
    {% extends 'template.html' %}
{% block content %}
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Log in</button>
       <p>
            Nie masz konta?
            <a href="{% url 'register' %}">Zarejestruj się</a>
        </p>
        <p>
            Jesteś firmą?
            <a href="{% url 'company_register' %}">Zarejestruj konto firmy</a>
        </p>
  </form>



{% endblock %}


</body>
</html>

GymShop/alledrogo/templates/orders.html
{% extends "template.html" %}
{% load custom_filters %}
{% block content %}
<div class="orders">
    <br>
    <h2>Moje zamówienia</h2>

    {% if zamowienia %}
        <ul class="order-list">
            {% for zamowienie in zamowienia %}
                <li class="order-item">
                    <h2>Numer zamówienia: {{ zamowienie.id }}</h2>
                    <h3>Dane osobowe:</h3>
                    <p>Imię: {{ zamowienie.imie }}</p>
                    <p>Nazwisko: {{ zamowienie.nazwisko }}</p>
                    <p>Numer telefonu: {{ zamowienie.numer_telefonu }}</p>
                    <h3>Adres Zamówienia:</h3>
                    <p>Ulica i numer domu: {{ zamowienie.ulica }}</p>
                    <p>Miasto: {{ zamowienie.miasto }}</p>
                    <p>Kod pocztowy: {{ zamowienie.kod_pocztowy }}</p>
                    <h3>Notatki od zamawiającego:</h3>
                    <p>{{ zamowienie.notatki }}</p>
                    <h3>Produkty:</h3>
                    <ul class="product-list">
                        {% for pozycja in zamowienie.pozycjazamowienia_set.all %}
                            <li class="product-item">
                                <div class="product-details">
                                    <h4>{{ pozycja.produkt.nazwa }}</h4>
                                    <p>Ilość: {{ pozycja.ilosc }}</p>
                                    <p>Cena jednostkowa: {{ pozycja.produkt.cena }} PLN</p>
                                    <p>Łączna cena: {{ pozycja.ilosc|mul:pozycja.produkt.cena|floatformat:2 }} PLN</p>
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                </li>
                <br>
                <br>
            {% endfor %}
        </ul>
    {% else %}
        <p>Nie masz żadnych zamówień.</p>
    {% endif %}
</div>
{% endblock %}

GymShop/alledrogo/templates/produkt_detail.html
{% extends "template.html" %}
{% load custom_filters %}
{% block content %}
<div class="product-detail-container">
    <div class="product-info">
        <h1>{{ produkt.nazwa }}</h1>
        <div class="rating-container">
            <span class="rating">{{ produkt.srednia_ocen|floatformat:1 }}</span>
            <div class="star-rating">
                ★★★★★
                <div class="star-rating-inner" style="width: {{ produkt.srednia_ocen|floatformat:1|mul:20 }}%;">★★★★★</div>
            </div>
        </div>
        <p>{{ produkt.opis }}</p>
        {% if produkt.zdjecie %}
        <img src="{{ produkt.zdjecie.url }}" class="product-image">
        {% endif %}
    </div>
    <div class="product-purchase">
        <form method="post" action="{% url 'dodaj_do_koszyka' produkt.id %}" class="purchase-form">
            {% csrf_token %}
            <h2>Produkt sprzedawany przez {{ produkt.firma }}</h2>
            <h1>Cena: {{produkt.cena}} PLN</h1>
            {% if user.is_authenticated %}
            <label for="quantity_{{ produkt.id }}">Ilość:</label>
            <input type="number" name="quantity" id="quantity_{{ produkt.id }}" min="1" value="1" style="width: 50px;"><br>
            <input type="submit" value="Dodaj do koszyka" class="btn">
            {%endif%}
        </form>
        {% if request.user.firma == produkt.firma %}
        <form method="post" action="{% url 'usun_produkt' produkt.id %}" class="purchase-form">

            {% csrf_token %}
            <input type="submit" value="Usuń produkt" class="btn" style="width: 400px; font-weight: bold" >
        </form>
        {% endif %}
        {% if user.is_authenticated %}
        <form method="post" action="{% url 'produkt_detail' produkt.id %}" class="rating-form">
            {% csrf_token %}
            <label for="ocena">Ocena:</label>
            <select name="ocena" id="ocena">
                {% for i in "12345" %}
                <option value="{{ i }}">{{ i }}</option>
                {% endfor %}
            </select>
            <label for="komentarz">Komentarz:</label>
            <textarea name="komentarz" id="komentarz"></textarea>
            <input type="submit" value="Dodaj ocenę" class="btn">
        </form>
        {%endif%}
        <div class="ratings-container">
            <h3>Oceny:</h3>
            <div class="ratings-box">
                {% for ocena in oceny %}
                <div class="rating-item">
                    <p><strong>{{ ocena.klient.username }}</strong>: {{ ocena.ocena }} ★</p>
                    <p>{{ ocena.komentarz }}</p>
                </div>
                {% endfor %}
            </div>
        </div>

    </div>
</div>
{% endblock %}

GymShop/alledrogo/templates/register.html
<!DOCTYPE html>
<html>
<head>
    <title>Rejestracja</title>
</head>
<body>
    {% extends "template.html" %}
    {% block content %}
    <form method="post">
        <h2>Rejestracja</h2>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Zaloguj</button>

    </form>
    {% endblock %}
</body>
</html>